
# **Pytorch Basic(Functions and Operations of Tensors)**



PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab.

First of all install those libraries which we use in next cells like Installing Pytorch for start working with pytorch and installing Numpy for performing numerical operations with data .So, Lets start 

In [1]:
!pip install numpy
!pip install torch

After installation Let's import them in our file

In [2]:
import numpy as np 
import torch

In [4]:
#Number
t1 = torch.tensor(4.)
t1.shape

torch.Size([])

Torch is basically used for processing with data more easy through Torch we able to creat Numbers , Matrix ,  2D-Matrix or any N - Dimensional Matrix. Above i just creat a tensor of a simple number.

In [5]:
t1

tensor(4.)

In [6]:
#Matrix
t2 = torch.tensor([1,2,3,4.])

Now we can create a Matrix with tensor. As we all kow that we can create Matrix with Numpy also but it gives us many facilities which we can see next 

In [7]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [8]:
# 2D - Matrix 
t3 = torch.tensor([
                   [1,2,3],
                   [4,6,7.]])

Creating 2D - Matrix

In [9]:
print(t3)
t3.shape

tensor([[1., 2., 3.],
        [4., 6., 7.]])


torch.Size([2, 3])

In [14]:
t4 = torch.tensor([[[1,2,3],[5,2.,2] , [9,8,4]]])

In [15]:
print(t4)
t4.shape

tensor([[[1., 2., 3.],
         [5., 2., 2.],
         [9., 8., 4.]]])


torch.Size([1, 3, 3])

We can create N- Dimensional Matrix with Torch 

****

**Converting Python Numpy as Pytorch Tensors**

In [18]:
array = np.array([1,2,3,4,5,6])

Creating a Numpy Array and convert it with Pytorch Tensor we see it next 

In [19]:
array

array([1, 2, 3, 4, 5, 6])

In [20]:
y = torch.from_numpy(array)

We can convert numoy array with Pytorch tensor through method
```
# torch.from_numpy()
```







In [21]:
y

tensor([1, 2, 3, 4, 5, 6])

In [24]:
# Converting again back to To the numpy from Tensors
z = y.numpy()
z

array([1, 2, 3, 4, 5, 6])

We can also convert a Tensor to a Numpy Array through `.numpy` function

**Tensor Operations and its Functions**

In [25]:
x = torch.tensor(4.)
w = torch.tensor(5. ,requires_grad=True)
b = torch.tensor(6. ,requires_grad=True)


Now we can create  three tensors like `x,w,b` and we set `requires_grad` True because it will be helpfull for taking derivatives of variables like at `x and b` `requires_grad` is True so that is why we can be able to take Derivatives of these two variables and we can not take deriative of x because we can not set `requires_grad` True . So, that's why we can't take derivative of `x`



In [26]:
y = x * w + b
y

tensor(26., grad_fn=<AddBackward0>)

Torch is so easy to do any task like as we can do in simple programming like we can add or multiply variables with very easy statements 

In [27]:
y.backward()

We use `y.backward` is because when we run this Torch is automatically solves derivatives of variables and than save it in `.grad` function.And we use that function below

In [28]:
print("dy/dx:" , x.grad)
print("dy/dw:" , w.grad)
print("dy/db:" , b.grad)

dy/dx: None
dy/dw: tensor(4.)
dy/db: tensor(1.)


**Tesor Functions**

In [32]:
y = torch.full((3,3) , 53)
y

tensor([[53, 53, 53],
        [53, 53, 53],
        [53, 53, 53]])

In Pytorch there is also many functions as there is in Numpy we can create many simple things easily with them Like here we use `.full` function where we give him a tuple that there is a `3` rows and `3` columns and all the elements of the matrix is `53`

In [34]:
y2 = torch.full((3,3) , 42)


Same here as we can do above 

In [35]:
concat = torch.cat((y , y2))

In [36]:
concat

tensor([[53, 53, 53],
        [53, 53, 53],
        [53, 53, 53],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]])

we can also concatenate two Matrices having same number of rows and columns .  

In [39]:
sin = torch.sin(t3)
sin

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.2794,  0.6570]])

we can also use Trignometry Operation is easily exceept to implement that how to calculate them. So, thes things makes Pytorch very Efficient and easy to use 

In [44]:
concat_reshape = concat.reshape(2,3,3)

In [45]:
concat_reshape

tensor([[[53, 53, 53],
         [53, 53, 53],
         [53, 53, 53]],

        [[42, 42, 42],
         [42, 42, 42],
         [42, 42, 42]]])

We can also reshape our matrix in a given form